### ISSUE TITLE
Things to think about when making directory search

### ISSUE THREAD

**Issue by allisonkong** [ASCIT/donut#10]
Just a list of things that came to mind (may update this later):
- Prefrosh emails should be hidden during rotation
- Gender options should **not** be limited to male/female (option to fill in their own string?)
  - Use an enum for gender (`Gender.Male`, `Gender.Female`, `Gender.Other`) so the gender is stored as an int in the database, and then have a second (nullable) column for gender_string so you can store a custom string if `Gender.Other` is used. 
- Search by zip code is kinda creepy, honestly (and also is pretty broken)
- A feature that would be cool is search-as-you-type (like google search)

**Comment by epelz** [comment]
As a note, we got rid of search by zip code (for non-admins). We replaced it with displaying hometown on the directory result, but you can't search by it.

**Comment by allisonkong** [comment]
Ah, didn't realize that was admin only.
