### ISSUE TITLE
Python 3?

### ISSUE THREAD

**Issue by allisonkong** [ASCIT/donut#12]
Just curious what your thoughts are on switching to Python 3 (now would be a good time to do it, before most of the code is actually written). From a quick glance at http://py3readiness.org/ it seems like everything we use is python3 ready (except mysql-python, but pymysql is an alternative that can be used). The end of life of python2 is intended to be 2020, and most active development is happening for python3.x with some functionality/packages being backported to 2.7.

**Comment by alphaz99** [comment]
It sounds like a good idea to me, it'll be good to extend the lifetime of the codebase since python3 is in use more.

**Comment by dqu123** [comment]
I think it would make sense to transition to Python 3.

**Comment by dqu123** [comment]
So we should install Python 3 and then redo the virtualenv with Python 3?

**Comment by allisonkong** [comment]
Yeah, experiment around with it for a bit and see what issues come up

**Comment by dqu123** [comment]
Okay, now python3.5 is installed, and I changed `import httplib` to `import http.client`,
but will need to change the MySQLdb import.
I will update the virtualenv instructions in README.md as well.
See #13 for details on this.

**Comment by dqu123** [comment]
Travis is reporting an issue in the tests, so we'll have to fix that too.
UPDATE: I got SQL Alchemy to work using mysql-connector-python instead of pymysql (couldn't get that to work on my first try). See requirements.txt.

**Comment by dqu123** [comment]
See #35
