### ISSUE TITLE
Incorrect width in course scheduler

### ISSUE THREAD

**Issue by koivyr** [ASCIT/donut#129]
<img width="500" alt="Screen Shot 2020-02-27 at 00 32 18" src="https://user-images.githubusercontent.com/26130897/75426101-c9dc1980-58f8-11ea-8e6a-4536b5f32986.png">
L174 should span but does not.

**Comment by calebsander** [comment]
This was intentional because it was a lot easier to code, but I can try to change it so width is not a per-day value

**Comment by koivyr** [comment]
I feel like some kid will probably submit this as an issue at some point haha 
Definitely not super necessary but would be nice to fix
