### ISSUE TITLE
course planner formatting

### ISSUE THREAD

**Issue by sl278** [ASCIT/donut#158]
the formatting isn't working, I'm unable to add classes past sophomore year

**Comment by calebsander** [comment]
What browser are you using? If the years don't all fit on your screen, you should be able to scroll down to the year you want to add to.

**Comment by sl278** [comment]
im on safari, this is what it looks like on my end. when I try to drag a class over the junior year slot it won't let me
<img width="678" alt="Screen Shot 2020-04-05 at 8 02 00 PM" src="https://user-images.githubusercontent.com/63214334/78513273-57bce700-7778-11ea-88aa-61ada202b0a5.png">

**Comment by koivyr** [comment]
I'd use Chrome if possible in the meantime while we fix this.
