### ISSUE TITLE
ARC Feedback - Course Concerns Emails

### ISSUE THREAD

**Issue by danineamati** [ASCIT/donut#161]
Really the ARC just needs an email with the Course/Subject in the email subject lines and the feedback message in the main body of the email.

Thank you so much in advance!

**Comment by calebsander** [comment]
@rlin0 I think this holds for all feedbacks. We currently have code to send update emails, but we can probably leverage the newsgroups code to CC the ASCIT/ARC/Devteam group on all messages.
