### ISSUE TITLE
Incompatible with mysql 8

### ISSUE THREAD

**Issue by dqu123** [ASCIT/donut#214]
Running into issues setting things up locally on mysql 8.0.22 (latest version).
@calebsander just FYI in case there's a need to upgrade, but my use case is using this code base as a personal service template for playing around with things and wanting the latest mysql if possible. I can work around it.

Do you know what version Donut is running? 
Also don't have consistent time to put into this, so may not be very responsive.

![image](https://user-images.githubusercontent.com/7023570/99197910-61bdb400-2763-11eb-8f1b-2c10a01f53fe.png)
```
david:template$ mysql --version
mysql  Ver 8.0.22 for macos10.15 on x86_64 (MySQL Community Server - GPL)
```
https://dev.mysql.com/doc/refman/8.0/en/keywords.html
![image](https://user-images.githubusercontent.com/7023570/99198474-c595ac00-2766-11eb-85ce-6286c3298e3a.png)

**Comment by calebsander** [comment]
We are using MariaDB:
```
$ mysql --version
mysql  Ver 15.1 Distrib 10.4.17-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2
```
This version of MariaDB is reasonably up to date (10.5 is the current one), but there are definitely some incompatibilities between MySQL and MariaDB. I'd rather not change the table name if it works in MariaDB.
