### ISSUE TITLE
Restricting the length of survey responses

### ISSUE THREAD

**Issue by ialexryan** [ASCIT/donut#24]
I was just going through the results of the recent ASCIT president special election (http://donut.caltech.edu/vote/results.php?survey_id=645) and I'm so freaking tired of scrolling through massive copy-pasted blocks of text.

Can I put up a PR to do some basic client-side check that prevents more than 500 characters from being entered? This has been a known bug for literally years.

**Comment by ialexryan** [comment]
I'm figuring this shouldn't take more than 5 minutes (at least to come up with something a non-dedicated non-CS major can't get around), please let me know if you think that won't be the case.

**Comment by lukejuusola** [comment]
If the goal is to stop abuse, probably changing rendering would be best. Maybe something expandable. See attached file. 
[expandable.txt](https://github.com/ASCIT/donut/files/525596/expandable.txt)

**Comment by alphaz99** [comment]
I think a char limit would be better - rendering solves the issue for the client but still causes issues for us in the backend. For example, the DB still has the full text. @ialexryan if you want to make a PR go ahead - one of us can also take care of it.

**Comment by allisonkong** [comment]
Just a heads up @ialexryan - this is not the repository that you are looking for. The current donut website is written in a php codebase that is not public. This repo was an effort to rewrite the website in python/flask, but is completely separate from what is actually running in prod.

**Comment by allisonkong** [comment]
I agree with @alphaz99 - we need to have a limit on the actual text, not how it's rendered.

**Comment by lukejuusola** [comment]
Then it needs to be done server side. I don't believe that trivial client side validation will deter people from writing in the script to Bee Movie. To me, it seems like the complaint is not that it's there, it's that you have to scroll past it.

**Comment by ialexryan** [comment]
oh god @dkong1796 really? Is it in a repository at all? How do changes get made to that codebase?

**Comment by allisonkong** [comment]
It's in a private github repo... you should ask Rahul or David for access.

**Comment by dqu123** [comment]
@alphaz99 @dkong1796 @lukejuusola  If we want to just do it in the database, can't we just add a CHECK constraint on the length of the writeins?

**Comment by allisonkong** [comment]
Does postgres enforce CHECK constraints? I know mysql ignores them altogether. If you did that, then you would throw an error whenever something exceeded the limit.

I think the ideal solution would include:
- Client check that says "you have x characters remaining", so the user actually knows that a limit exists (it should not truncate/reject silently or in a way that's not obvious).
- If a request contains a string that exceeds the limit, either truncate or reject the string in code. MySQL has a default truncation behavior if strict mode is not turned on, but I don't know what postgres does.
- You could also consider changing the data type from text to varchar.

**Comment by dqu123** [comment]
Hi @ialexryan, 
We took care of this over the break, so there shouldn't be any problems anymore. 
Please let us know if you find any bugs with our implementation.
