### ISSUE TITLE
Enabling HTTPS

### ISSUE THREAD

**Issue by allisonkong** [ASCIT/donut#36]
Is it feasible to install a TLS certificate so that donut traffic is encrypted? Currently all logins are sending passwords in plaintext. You can purchase a TLS certificate from IMSS (talk to RuthAnne; I think it's $50/year or something very reasonable).

**Comment by RobertEng** [comment]
Good idea. I'll look into this.

**Comment by calebsander** [comment]
Are you familiar with https://letsencrypt.org/ ? I use this and it's pretty convenient. It's free, you just have to run it once every 3 months.

**Comment by dqu123** [comment]
@calebsander, this looks like a nice solution. 
Is this what you use: https://certbot.eff.org/#debianother-apache
(Apparently our server is Debian 5.0)

**Comment by calebsander** [comment]
I think it's Ubuntu 14.04, so you can use the Ubuntu-specific instructions: https://certbot.eff.org/#ubuntutrusty-other. I don't think you want the Apache-specific version.

This is the command I run, but I think I set this up before they made it really simple to renew.
````bash
sudo letsencrypt certonly --text --standalone --standalone-supported-challenges tls-sni-01 --domain calebsander.com,www.calebsander.com --email [my-email] --agree-tos --renew-by-default
sudo cp /etc/letsencrypt/live/calebsander.com/privkey.pem ~/server/key.pem
sudo cp /etc/letsencrypt/live/calebsander.com/cert.pem ~/server/cert.pem
sudo cp /etc/letsencrypt/live/calebsander.com/chain.pem ~/server/chain.pem
````

**Comment by dqu123** [comment]
I should clarify the legacy server I think is Debian 5.0.
You're right that the rewrite is Ubuntu 14.04.

**Comment by calebsander** [comment]
Yeah, I then I would follow the Debian instructions for the legacy one. I have only ever used it with Ubuntu, but I imagine they should be very similar.

**Comment by allisonkong** [comment]
Yeah, either way would be fine.

**Comment by calebsander** [comment]
HTTPS is working on [beta.donut.caltech.edu](https://beta.donut.caltech.edu/) now. We went with Let's Encrypt.
