### ISSUE TITLE
Conflicting tables "positions" and "group_positions"

### ISSUE THREAD

**Issue by calebsander** [ASCIT/donut#46]
The schemas are currently as follows in `donut.sql`:
````sql
CREATE TABLE positions (
    group_id INT         NOT NULL,
    pos_id   INT         NOT NULL AUTO_INCREMENT,
    pos_name VARCHAR(32) NOT NULL,
    PRIMARY KEY (pos_id),
    FOREIGN KEY (group_id) REFERENCES groups(group_id)
);
CREATE TABLE group_positions (
    pos_id      INT NOT NULL,
    group_id    INT NOT NULL,
    send        BOOLEAN DEFAULT FALSE, -- Toggles whether or not this position
                                       -- can send emails to group
    control     BOOLEAN DEFAULT FALSE, -- Toggles whether or not this position
                                       -- has admin control over group
    receive     BOOLEAN DEFAULT TRUE,  -- Toggles if this position receives
                                       -- emails from this group
    PRIMARY KEY (pos_id, group_id),
    FOREIGN KEY (pos_id) REFERENCES positions(pos_id),
    FOREIGN KEY (group_id) REFERENCES groups(group_id)
);
````
Both tables link a group id to a position id, meaning that they are redundant and can contain conflicting information. There are two solutions I see:
1. Remove `group_id` from `positions`. This way, a position like "President" could exist on multiple groups. This would allow for functionality like Donut Legacy currently has, where you can search for a single campus position across groups.
2. Remove the `positions` table and put `pos_name` instead of `pos_id` on `group_positions`. This would simplify the schema a bit but make searching for a specific position less efficient.

Thoughts?

**Comment by majesticfish** [comment]
This is not actually conflicting information here's why:

The `positions` table references positions on campus. For example "ASCIT Secretary" would be a row on this table whose group_id references ASCIT and pos_name is "Secretary"

The `group_positions` table references how certain positions are allowed to post and receive emails from, or just generally belong to a certain group. For example an row on this table might describe the fact that "The ASCIT President has permission to send emails to the Donut Dev Team". Here the position is primarily associated to "ASCIT" the group, but is a member of "Donut Dev Team" in that it can send emails and such to it.

This is particularly useful for ASCIT secretary which is a position that should be allowed to send emails to multiple groups that regular people cannot. 
Sorry if this wasn't made clear

@RobertEng This was what was intended correct?
