### ISSUE TITLE
Marketplace search is broken in Python 3

### ISSUE THREAD

**Issue by calebsander** [ASCIT/donut#50]
The `sorted()` function in Python 3 doesn't take a `cmp` argument, so an error is thrown when executing a marketplace search (line 601 of `donut/modules/marketplace/helpers.py`). To reproduce: http://localhost:9000/marketplace/search?q=calculus&cat=all. Consider using [`cmp_to_key()`](https://docs.python.org/3/library/functools.html#functools.cmp_to_key)?

**Comment by tjleing** [comment]
Yeah, sorry about that.  It's fixed on marketplace, and when that gets merged back into master, the bug will be gone.
