### ISSUE TITLE
User Permissions

### ISSUE THREAD

**Issue by dqu123** [ASCIT/donut#60]
We need to design a permissions system that can handle Donut's various use cases.

#### Design
- [ ] Questions to answer
  - [ ] Should all permissions use one system / web portal?
    - David: leaning towards yes to standardize permissions interface. I raise this question because the legacy design is not this way.
  - [ ] Should we add timestamps for temporary permissions?
- [ ] [David's design](https://docs.google.com/document/d/1Ykw7wJefM6xlAN1OPoMIyVJSOJxusteOEInJ8LL5CW0/edit) (put in comment mode because this is a public repo)
  - Group specific permissions
    - Devteam privileges
    - RA privileges
  - Position specific permissions
    - ASCIT Secretary
    - IHC Chair
  - User specific
    - Marketplace items
    - This can be done just by checking the current user_id and not needing check_permission()
    - Access to specific surveys

#### Implementation
- [ ] Update user auth module to support design
  - [ ] Update [get_permissions](https://github.com/ASCIT/donut/blob/master/donut/auth_utils.py#L314)
  - [ ] Update [check_permissions](https://github.com/ASCIT/donut/blob/master/donut/auth_utils.py#L338)

**Comment by joshc** [comment]
@dqu123 should we add sean since he's working with groups (and permissions?) or is that not relevant?

**Comment by majesticfish** [comment]
After discussing with @davistardif and @mhuynh5757, we think that the best way to handle permissions is as follows. Firstly, every person that is in a group will have an associated position. At the beginning of each session we grab all the user's held positions, and the user id. Eac permission will be done on a case by case basis. For example if only members of the ARC can view complaints, then the software simply checks if among the list of position there is a position that belongs to the ARC. If specifically the IHC chair can send to UG-all, then the software checks if the user is IHC Chair, etc.

**Comment by majesticfish** [comment]
**UPDATE**:
We are also updating the way that we do positions being linked to other positions. Since group membership will always be associated with a position, when someone is in Group X because he has position A in group Y, then he will be assigned a position B in X, and the position A will be linked to position B in by a position_relations table.
